event_dict2 = {
	'actnow' : ['ActNow', '(int commID)'],
	'actionfailed' : ['ActionFailed', '(int commID, String message)'],
	'adventurerarrived' : ['AdventurerArrived', '(int commID, int adventurer, int player)'],
	'adventurerdamaged' : ['AdventurerDamaged', '(int commID, int adventurer, int amount, int player)'],
	'adventurerdrawn' : ['AdventurerDrawn', '(int commID, int adventurer)'],
	'adventurerfled' : ['AdventurerFled', '(int commID, int adventurer)'],
	'adventurerhealed' : ['AdventurerHealed', '(int commID, int amount, int priest, int target)'],
	'adventurerimprisoned' : ['AdventurerImprisoned', '(int commID, int adventurer, int player)'],
	'biddingstarted' : ['BiddingStarted', '(int commID)'],
	'config' : ['Config', '(int commID, String config)'],
	'defendyourself' : ['DefendYourself', '(int commID)'],
	'digtunnel' : ['DigTunnel', '(int commID)'],
	'evilnesschanged' : ['EvilnessChanged', '(int commID, int amount, int player)'],
	'foodchanged' : ['FoodChanged', '(int commID, int amount, int player)'],
	'gameend' : ['GameEnd', '(int commID, int player, int points)'],
	'gamestarted' : ['GameStarted', '(int commID)'],
	'goldchanged' : ['GoldChanged', '(int commID, int amount, int player)'],
	'selectmonster' : ['SelectMonster', '(int commID)'],
	'impschanged' : ['ImpsChanged', '(int commID, int amount, int player)'],
	'left' : ['Left', '(int commID, int player)'],
	'monsterdrawn' : ['MonsterDrawn', '(int commID, int monster)'],
	'monsterhired' : ['MonsterHired', '(int commID, int monster, int player)'],
	'monsterplaced' : ['MonsterPlaced', '(int commID, int monster, int player)'],
	'nextround' : ['NextRound', '(int commID, int round)'],
	'nextyear': ['NextYear', '(int commID, int year)'],
	'bidplaced' : ['BidPlaced', '(int commID, BidType bid, int player, int slot)'],
	'bidretrieved' : ['BidRetrieved', '(int commID, BidType bid, int player)'],
	'player' : ['Player', '(int commID, String name, int player)'],
	'registrationaborted' : ['RegistrationAborted', '(int commID,)'],
	'tunnelconquered' : ['TunnelConquered', '(int commID, int adventurer, int x, int y)'],
	'tunneldug' : ['TunnelDug', '(int commID, int player, int x, int y)'],
	'placeroom' : ['PlaceRoom', '(int commID)'],
	'battlegroundset' : ['BattleGroundSet', '(int commID, int player, int x, int y)'],
	'roomactivated' : ['RoomActivated', '(int commID, int player, int room)'],
	'roomdrawn' : ['RoomDrawn', '(int commID, int room)'],
	'trapacquired' : ['TrapAcquired', '(int commID, int player, int trap)'],
	'trapplaced' : ['TrapPlaced', '(int commID, int player, int trap)'],
}

action_dict2 = {
	'endturn' : ['EndTurn', '()'],
	'leave' : ['Leave', '()'],
	'monster' : ['Monster', '(int monster)'],
	'monstertargeted' : ['MonsterTargeted', '(int monster, int position)'],
	'hiremonster' : ['HireMonster', '(int monster)'],
	'placebid' : ['PlaceBid', '(BidType bid, int number)'],
	'register' : ['Register', '(String playerName)'],
	'startgame' : ['StartGame', '()'],
	'activateroom' : ['ActivateRoom', '(int room)'],
	'battleground' : ['BattleGround', '(int x, int y)'],
	'digtunnel' : ['DigTunnel', '(int x, int y)'],
	'trap' : ['Trap', '(int trapID)'],
	'buildroom' : ['BuildRoom', '(int x, int y, int roomID)'],
}



event_dict = {
	'actnow' : event_dict2['actnow'],
	'an' : event_dict2['actnow'],
	'actionfailed' : event_dict2['actionfailed'],
	'af' : event_dict2['actionfailed'],
	'adventurerarrived' : event_dict2['adventurerarrived'],
	'aa' : event_dict2['adventurerarrived'],
	'advarr' : event_dict2['adventurerarrived'],
	'adva' : event_dict2['adventurerarrived'],
	'aarr' : event_dict2['adventurerarrived'],
	'adar' : event_dict2['adventurerarrived'],
	'adventurerdamaged' : event_dict2['adventurerdamaged'],
	'ada' : event_dict2['adventurerdamaged'],
	'advdam' : event_dict2['adventurerdamaged'],
	'adventurerdrawn' : event_dict2['adventurerdrawn'],
	'advdra' : event_dict2['adventurerdrawn'],
	'adventurerfled' : event_dict2['adventurerfled'],
	'af' : event_dict2['adventurerfled'],
	'advf' : event_dict2['adventurerfled'],
	'adventurerhealed' : event_dict2['adventurerhealed'],
	'ah' : event_dict2['adventurerhealed'],
	'advheal' : event_dict2['adventurerhealed'],
	'advheal' : event_dict2['adventurerhealed'],
	'adventurerimprisoned' : event_dict2['adventurerimprisoned'],
	'ai' : event_dict2['adventurerimprisoned'],
	'advimp' : event_dict2['adventurerimprisoned'],
	'advimpr' : event_dict2['adventurerimprisoned'],
	'advi' : event_dict2['adventurerimprisoned'],
	'biddingstarted' : event_dict2['biddingstarted'],
	'bs' : event_dict2['biddingstarted'],
	'bidstart' : event_dict2['biddingstarted'],
	'config' : event_dict2['config'],
	'c' : event_dict2['config'],
	'co' : event_dict2['config'],
	'con' : event_dict2['config'],
	'defendyourself' : event_dict2['defendyourself'],
	'dy' : event_dict2['defendyourself'],
	'defyou' : event_dict2['defendyourself'],
	'digtunnel' : event_dict2['digtunnel'],
	'dt' : event_dict2['digtunnel'],
	'dig' : event_dict2['digtunnel'],
	'evilnesschanged' : event_dict2['evilnesschanged'],
	'e' : event_dict2['evilnesschanged'],
	'ec' : event_dict2['evilnesschanged'],
	'foodchanged' : event_dict2['foodchanged'],
	'f' : event_dict2['foodchanged'],
	'fc' : event_dict2['foodchanged'],
	'gameend' : event_dict2['gameend'],
	'ge' : event_dict2['gameend'],
	'gend' : event_dict2['gameend'],
	'gamestarted' : event_dict2['gamestarted'],
	'gs' : event_dict2['gamestarted'],
	'gstart' : event_dict2['gamestarted'],
	'goldchanged' : event_dict2['goldchanged'],
	'gc' : event_dict2['goldchanged'],
	'selectmonster' : event_dict2['selectmonster'],
	'sm' : event_dict2['selectmonster'],
	's' : event_dict2['selectmonster'],
	'impschanged' : event_dict2['impschanged'],
	'ic' : event_dict2['impschanged'],
	'i' : event_dict2['impschanged'],
	'left' : event_dict2['left'],
	'l' : event_dict2['left'],
	'monsterdrawn' : event_dict2['monsterdrawn'],
	'md' : event_dict2['monsterdrawn'],
	'mdraw' : event_dict2['monsterdrawn'],
	'monsterhired' : event_dict2['monsterhired'],
	'mh' : event_dict2['monsterhired'],
	'mhire' : event_dict2['monsterhired'],
	'monsterplaced' : event_dict2['monsterplaced'],
	'mp' : event_dict2['monsterplaced'],
	'mplace' : event_dict2['monsterplaced'],
	'nextround' : event_dict2['nextround'],
	'nr' : event_dict2['nextround'],
	'nextyear' : event_dict2['nextyear'],
	'ny' : event_dict2['nextyear'],
	'bidplaced' : event_dict2['bidplaced'],
	'bp' : event_dict2['bidplaced'],
	'bidretrieved' : event_dict2['bidretrieved'],
	'bret' : event_dict2['bidretrieved'],
	'br' : event_dict2['bidretrieved'],
	'player' : event_dict2['player'],
	'p' : event_dict2['player'],
	'registrationaborted' : event_dict2['registrationaborted'],
	'ra' : event_dict2['registrationaborted'],
	'regab' : event_dict2['registrationaborted'],
	'tunnelconquered' : event_dict2['tunnelconquered'],
	'tc' : event_dict2['tunnelconquered'],
	'tuco' : event_dict2['tunnelconquered'],
	'tunneldug' : event_dict2['tunneldug'],
	'td' : event_dict2['tunneldug'],
	'tudu' : event_dict2['tunneldug'],
	'placeroom' : event_dict2['placeroom'],
	'pr' : event_dict2['placeroom'],
	'plro' : event_dict2['placeroom'],
	'battlegroundset' : event_dict2['battlegroundset'],
	'bgs' : event_dict2['battlegroundset'],
	'roomactivated' : event_dict2['roomactivated'],
	'ra' : event_dict2['roomactivated'],
	'roac' : event_dict2['roomactivated'],
	'roomdrawn' : event_dict2['roomdrawn'],
	'rd' : event_dict2['roomdrawn'],
	'rodr' : event_dict2['roomdrawn'],
	'trapacquired' : event_dict2['trapacquired'],
	'ta' : event_dict2['trapacquired'],
	'traq' : event_dict2['trapacquired'],
	'trapplaced' : event_dict2['trapplaced'],
	'tp' : event_dict2['trapplaced'],
	'trpl' : event_dict2['trapplaced'],
}



action_dict = {
	'endturn' : action_dict2['endturn'],
	'e' : action_dict2['endturn'],
	'et' : action_dict2['endturn'],
	'leave' : action_dict2['leave'],
	'l' : action_dict2['leave'],
	'monster' : action_dict2['monster'],
	'm' : action_dict2['monster'],
	'monstertargeted' : action_dict2['monstertargeted'],
	'mt' : action_dict2['monstertargeted'],
	'hiremonster' : action_dict2['hiremonster'],
	'h' : action_dict2['hiremonster'],
	'hm' : action_dict2['hiremonster'],
	'placebid' : action_dict2['placebid'],
	'p' : action_dict2['placebid'],
	'pb' : action_dict2['placebid'],
	'register' : action_dict2['register'],
	'reg' : action_dict2['register'],
	'r' : action_dict2['register'],
	'reg' : action_dict2['register'],
	'startgame' : action_dict2['startgame'],
	's' : action_dict2['startgame'],
	'sg' : action_dict2['startgame'],
	'activateroom' : action_dict2['activateroom'],
	'a' : action_dict2['activateroom'],
	'ar' : action_dict2['activateroom'],
	'battleground' : action_dict2['battleground'],
	'b' : action_dict2['battleground'],
	'bg' : action_dict2['battleground'],
	'digtunnel' : action_dict2['digtunnel'],
	'd' : action_dict2['digtunnel'],
	'dt' : action_dict2['digtunnel'],
	'dg' : action_dict2['digtunnel'],
	'trap' : action_dict2['trap'],
	't' : action_dict2['trap'],
	'buildroom' : action_dict2['buildroom'],
	'b' : action_dict2['buildroom'],
	'br' : action_dict2['buildroom'],
}